import { test, expect, _electron as electron } from '@playwright/test'

test('calendar views: week/month/day, visibility toggle, screenshots', async () => {
  const app = await electron.launch({ args: ['.'], env: { ...process.env, MULTICALS_MOCK: '1' } })
  const page = await app.firstWindow()
  await page.setViewportSize({ width: 1200, height: 800 })
  const blocks = page.getByTestId('event-block')

  // Week view (default) shows events from both isolated accounts.
  await expect(page.getByTestId('view-switch-week')).toHaveAttribute('aria-selected', 'true')
  await expect(blocks.filter({ hasText: 'Daily standup' }).first()).toBeVisible()
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(1)
  await expect(page.locator('[data-testid="event-block"][data-account-id="work"]').first()).toBeAttached()
  await expect(page.locator('[data-testid="event-block"][data-account-id="personal"]').first()).toBeAttached()
  await expect(page.getByTestId('sidebar-account-work')).toContainText('me@work.example')
  await expect(page.getByTestId('sidebar-account-personal')).toContainText('Holidays')
  await expect(page.getByTestId('sidebar-account-work')).not.toContainText('Holidays')
  await page.screenshot({ path: 'e2e/screens/unit6-week.png' })

  await page.getByTestId('view-switch-month').click()
  await expect(page.locator('.mg-cell')).toHaveCount(42)
  await expect(blocks.filter({ hasText: 'Sprint planning' })).toHaveCount(1)
  await page.screenshot({ path: 'e2e/screens/unit6-month.png' })

  await page.getByTestId('view-switch-day').click()
  await expect(page.locator('.tg-col')).toHaveCount(1)
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(1)
  await page.keyboard.press('ArrowRight')
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(0)
  await page.keyboard.press('ArrowRight')
  await expect(blocks.filter({ hasText: 'Dinner with friends' })).not.toHaveClass(/is-past/)
  await page.keyboard.press('t')
  await page.keyboard.press('ArrowLeft')
  await expect(blocks.filter({ hasText: 'Daily standup' })).toHaveClass(/is-past/)
  await page.keyboard.press('t')
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(1)

  // 3-day view: 3 columns from the selected date, h/l page by 3 days.
  await page.getByTestId('view-switch-3day').click()
  await expect(page.locator('.tg-col')).toHaveCount(3)
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(1)
  await page.screenshot({ path: 'e2e/screens/3day.png' })
  await page.keyboard.press('l')
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(0)
  await page.keyboard.press('h')
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(1)
  await page.keyboard.press('d')
  await page.keyboard.press('3')
  await expect(page.getByTestId('view-switch-3day')).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByTestId('statusbar')).toContainText('3day')

  // Hiding the personal calendar removes only its events.
  await page.getByTestId('view-switch-week').click()
  await page.getByTestId('sidebar-calendar-personal-p-main').uncheck()
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(0)
  await expect(blocks.filter({ hasText: 'Daily standup' }).first()).toBeVisible()
  await page.getByTestId('sidebar-calendar-personal-p-main').check()
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(1)

  // Account sections collapse/expand from their header.
  const personalToggle = page.getByTestId('sidebar-account-toggle-personal')
  await personalToggle.click()
  await expect(personalToggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByTestId('sidebar-calendar-personal-p-main')).toBeHidden()
  await expect(page.getByTestId('sidebar-account-work').locator('input[type=checkbox]').first()).toBeVisible()
  await personalToggle.click()
  await expect(personalToggle).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByTestId('sidebar-calendar-personal-p-main')).toBeVisible()

  // vim keys: d/w/m switch views, h/l move, n opens the editor, i toggles invites.
  await page.keyboard.press('m')
  await expect(page.getByTestId('view-switch-month')).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('d')
  await expect(page.locator('.tg-col')).toHaveCount(1)
  await page.keyboard.press('l')
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(0)
  await page.keyboard.press('h')
  await expect(blocks.filter({ hasText: 'Gym' })).toHaveCount(1)
  await page.keyboard.press('w')
  await expect(page.getByTestId('statusbar')).toContainText('week')
  await page.keyboard.press('i')
  await expect(page.locator('.invites-panel')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.keyboard.press('n')
  await expect(page.getByTestId('editor')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('editor')).toHaveCount(0)

  // Theme picker in Settings switches the palette and survives a reload.
  await page.getByRole('button', { name: 'Settings' }).click()
  await page.getByTestId('settings-tab-themes').click()
  await page.waitForTimeout(300)
  await page.screenshot({ path: 'e2e/screens/theme-settings.png' })
  await page.getByTestId('theme-tokyo').click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'tokyo')
  await page.keyboard.press('Escape')
  await page.waitForTimeout(200)
  await page.screenshot({ path: 'e2e/screens/theme-tokyo.png' })
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'tokyo')
  await page.evaluate(() => localStorage.removeItem('multicals-theme'))
  await app.close()
})
